### ISSUE TITLE
Rewards DB values not populated by token-replace.ps1

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/TailwindTraders-Backend#60]
When generating the values file using the `Generate-Config.ps1` and `token-replace.ps1` scripts, the rewards DB values are not populated. This seems to invalidate the values file.

example:

```
    profile:
      host: ttsqlservervk7einhhudcse.database.windows.net
      port: "1433"
      catalog: profile
      user: sqladmin
      pwd: **********
    rewards:
      host: {{dbhostrewards}}
      port: "1433"
      catalog: rewards
      user: {{dbuserrewards}}
      pwd: {{dbpwdrewards}}
```

I would be happy to PR the fix but am not sure on the needed DB values.
